close all, clear all,
addpath('./data/aniage');
addpath('./data/Malaysia_male');
addpath('./mask/V2/gap_num');
addpath('./mask/V2/marker_num_V2');

figure_tra=0;

mask_list={
'1.txt',...
'2.txt',...
'3.txt',...
'4_0.txt',...
'5.txt',...
'6.txt',...
'7.txt',...
'8.txt',...
'9.txt',...
'10.txt',...
'11.txt',...
'12.txt',...
'13.txt',...
'14.txt',...
};
 

MAE_T1_marker2frame=[];
AVG_avg_mae_T1=0;
MAE_PLOS1_marker2frame=[];
AVG_avg_mae_plos1=0;

epoch=size(mask_list,2);
for e=1:epoch
    formatSpec0='epoch %d\n';
    fprintf(formatSpec0,e);
    missing_mask_file=mask_list{e};
    [avg_mae_T1,avg_mae_plos1]=call_test4data(missing_mask_file);
    MAE_T1_marker2frame=[MAE_T1_marker2frame,avg_mae_T1];
    AVG_avg_mae_T1=AVG_avg_mae_T1+avg_mae_T1/epoch;
    MAE_PLOS1_marker2frame=[MAE_PLOS1_marker2frame,avg_mae_plos1];
    AVG_avg_mae_plos1=AVG_avg_mae_plos1+avg_mae_plos1/epoch;
end
    